- README.md
Commit ve branch isimlendirme formatı eklendi. Githubta bir respositoriesa sıfırdan pull request yapmak eklendi
> [feature] - [2] - [semver:minor] - Git ve branch formatları eklendi

- Interns/UfukYetiskin.md
Adımlar izlenerek Pull request yapıldı.
1- Master branch pull yapıldı.
2- Master branch üzerinden git checkout -b bugfix/8 ile branch oluşturuldu.
3- Intern dosyası eklendi ve commit edildi. Push edildi git push origin bugfix/8 üzerinden
4- Pull request yapmadan önce git rebase master yapıldı ve conflict hatası alınmadı.
5- Pull request yapıldı.
> Bugfix8 | Intern Dosyası oluşturuldu. Doküman içi düzenlendi.

- Interns/UfukYetiskin.md
[Diary]-[Ufuk Yetişkin]-[28.03.2022]-to-[01.03.2022]
günlük PR'lar toplu şekilde pushlandı.
> [Diary]-[Ufuk Yetişkin]-[28.03.2022]-to-[01.03.2022]

- Interns/UfukYetiskin.md
[Diary]-[Ufuk Yetişkin-[06.04.2022-to-08.04.2022]
> [Diary]-[Ufuk Yetişkin-[06.04.2022-to-08.04.2022]

- Interns/MuhammetDuzenli.md
- README.md
> [feature] - [88] - [semver:minor] - diary eklendi

- Interns/SelinAytenCengiz.md
- README.md
01.08.2022 , 02.08.2022  ve 03.08.2022  için diary eklendi #82
> [feature] - [82] - [semver:minor] - diary eklendi

- Interns/KeremErkubilay.md
- README.md
#86  İlk üç gün için diary eklendi.
> [feature] - [86] - [semver:minor] - Diary eklendi

- Interns/FelatAslan.md
- README.md
> [feature] - [92] - [semver:minor] - diary eklendi

- Interns/ÖmerHamsi.md
> [feature] - [120] - [semver:minor] - daily eklendi.

- Interns/MuhammetDuzenli.md
> [feature] - [122] - [semver:minor] - Diary güncellemesi

- Interns/BurakKucuk.md
- README.md
> [feature] - [89] - [semver:minor] - diary eklendi

- Interns/AliHanPertek.md
- README.md
> [feature] - [107] - [semver:minor] - diary eklendi

- Interns/SimgeTerzioglu.md
> [feature] - [126] - [semver:minor] - Diary eklendi

- Interns/ErayDanaci.md
- README.md
> [feature] - [140] - [semver:minor] - diary eklendi

- Interns/SafaCanPehlivan.md
> [feature] - [143] - [semver:minor] - diary güncellendi

- Interns/FelatAslan.md
> [feature] - [147] - [semver:minor] - diary güncellendi

- Interns/AliHanPertek.md
> [feature] - [136] - [semver:minor] - diary eklendi

- Interns/SelinAytenCengiz.md
> [feature] - [154] - [semver:minor] - diary güncellendi

- Interns/BurakKucuk.md
> [feature] - [152] - [semver:minor] - diary güncellendi 

- Interns/ÖmerHamsi.md
> [feature] - [159] - [semver:minor] - günlük yapılan çalışmalar eklendi.

- Interns/MuhammetDuzenli.md
> [feature] - [160] - [semver:minor] - diary güncellendi

- Interns/BurakKucuk.md
> [feature] - [179] - [semver:minor] - Diary eklendi.

- Interns/UmmugulsumErol.md
04.08.2022 ve 05.08.2022 tarihlerinin günlükleri eklendi. #125
> [feature] - [125] - [semver:minor] - diary eklendi

- Interns/OmerUcuncu.md
> [feature] - [162] - [semver:minor] - Diary güncellendi

- Interns/FelatAslan.md
> [feature] - [157] - [semver:minor] - diary güncellendi

- Interns/SimgeTerzioglu.md
> [feature] - [164] - [semver:minor] - diary güncellendi

- Interns/AliHanPertek.md
> [feature] - [166] - [semver:minor] - diary güncellendi

- Interns/ErayDanaci.md
> [feature] - [168] - [semver:minor] - diary güncellendi

- Interns/KeremErkubilay.md
5 Ağustos Cuma gününün günlüğü eklendi.
> [feature] - [169] - [semver:minor] - Diary Update

- Interns/EsraYelmen.md
> [feature] - [181] - [semver:minor] - diary güncellendi

- Interns/AbdullahBodur.md
> [feature] - [184] - [semver:minor] - diary güncellendi

- Interns/MuhammetDuzenli.md
> [feature] - [188] - [semver:minor] - diary güncellendi

- Interns/ÖmerHamsi.md
> [feature] - [194] - [semver:minor] - diary güncellendi

- Interns/SimgeTerzioglu.md
> [feature] - [199] - [semver:minor] - Diary güncellendi.

- Interns/FelatAslan.md
> [feature] - [192] - [semver:minor] - diary güncellendi

- Interns/BurakKucuk.md
> [feature] - [204] - [semver:minor] - Diary güncellendi.

- Interns/ErayDanaci.md
> [feature] - [197] - [semver:minor] - diary güncellendi

- Interns/AliHanPertek.md
> [feature] - [198] - [semver:minor] - diary güncellendi.

- Interns/ÖmerHamsi.md
> [feature] - [213] - [semver:minor] - diary eklendi

- Interns/UmmugulsumErol.md
08.08.2022 ve 09.08.2022 tarihlerinin günlükleri eklendi. #210
> [feature] - [210] - [semver:minor] - diary eklendi

- Interns/SimgeTerzioglu.md
> [feature] - [212] - [semver:minor] - Diary eklendi

- Interns/ErayDanaci.md
> [feature]-[218]-[semver:minor]- Diary güncellendi

- Interns/MuhammetDuzenli.md
> [feature] - [224] - [semver:minor] - diary güncellendi

- Interns/AliHanPertek.md
> [feature]-[222]-[semver:minor]-diary güncellendi.

- Interns/EsraYelmen.md
> [feature] - [220] - [semver:minor] - diary güncellendi

- Interns/FelatAslan.md
> [feature] - [208] - [semver:minor] - diary güncellendi

- Interns/MuhammetDuzenli.md
> [feature] - [232] - [semver:minor] - diary güncellendi

- Interns/AliHanPertek.md
> [feature]-[234]-[semver:minor]-diary güncellendi

- Interns/ErayDanaci.md
> [feature]-[241]-[semver:minor]-diary güncellendi

- Interns/SimgeTerzioglu.md
> [feature]-[239]-[semver:minor]-Diary güncellendi

- Interns/ÖmerHamsi.md
> [feature]-[236]-[semver:minor]-diary güncellendi

- Interns/EsraYelmen.md
> [feature]-[243]-[semver:minor]-diary güncellendi

- Interns/SelinAytenCengiz.md
> [feature]-[238]-[semver:minor]-Diary güncellendi

- Interns/FelatAslan.md
> [feature]-[250]-[semver:minor]-Diary güncellendi

- Interns/SelinAytenCengiz.md
> [feature]-[259]-[semver:minor]-Diary güncellendi

- Interns/SimgeTerzioglu.md
> [feature]-[266]-[semver:minor]-Diary güncellendi

- Interns/FelatAslan.md
> [feature]-[257]-[semver:minor]-Diary güncellendi

- Interns/ÖmerHamsi.md
> [feature]-[270]-[semver:minor]-Diary güncellendi

- Interns/OmerUcuncu.md
> [feature]-[254]-[semver:minor]-Diary güncellendi.

- Interns/MuhammetDuzenli.md
> [feature] - [275] - [semver:minor] - diary güncellendi

- Interns/UmmugulsumErol.md
10.08.2022 ve 11.08.2022 tarihlerinin günlükleri eklendi. #272
> [feature]-[272]-[semver:minor]-Diary güncellendi

- Interns/EsraYelmen.md
> [feature] - [278] - [semver:minor] - diary güncellendi

- Interns/AliHanPertek.md
> [feature]-[263]-[semver:minor]-Diary güncellendi

- Interns/RahimeTurkmen.md
> [feature]-[252]-[semver:minor]-Diary update

- Interns/BernaAkdoganlar.md
- README.md
> [feature] - [283] - [semver:minor] - Diary güncellendi.

- Interns/ErayDanaci.md
> [feature]-[262]-[semver:minor]-Diary güncellendi

- Interns/BurakKucuk.md
> [feature]-[261]-[semver:minor]-Diary güncellendi

- Interns/FelatAslan.md
> [feature]-[286]-[semver:minor]-Diary güncellendi

- Interns/MuhammetDuzenli.md
> [feature] - [296] - [semver:minor] - Diary güncellendi

- Interns/ErayDanaci.md
> [feature]-[294]-[semver:minor]-Diary güncellendi

- Interns/SimgeTerzioglu.md
> [feature]-[302]-[semver:minor]-Diary güncellendi

- Interns/BurakKucuk.md
> [feature]-[300]-[semver:minor]-Diary güncellendi

- Interns/RahimeTurkmen.md
> [feature]-[292]-[semver:minor]-Diary update

- Interns/AliHanPertek.md
> [feature]-[298]-[semver:minor]-Diary güncellendi

- Interns/OmerUcuncu.md
> [feature]-[285]-[semver:minor]-Diary güncellendi.

- Interns/KeremErkubilay.md
> [feature]-[289]-[semver:minor]-Diary güncellendi

- Interns/AbdullahBodur.md
> [feature]-[306]-[semver:minor]-Diary güncellendi

- Interns/EsraYelmen.md
> [feature]-[318]-[semver:minor]-Diary güncellendi

- Interns/ÖmerHamsi.md
> [feature]-[313]-[semver:minor]-Diary güncellendi

- Interns/ErayDanaci.md
> [feature]-[309]-[semver:minor]-Diary güncellendi

- Interns/KeremErkubilay.md
> [feature]-[315]-[semver:minor]-Diary güncellendi

- Interns/MuhammetDuzenli.md
> [feature]-[311]-[semver:minor]-Diary güncellendi

- Interns/OmerUcuncu.md
> [feature]-[308]-[semver:minor]-Diary güncellendi.

- Interns/UmmugulsumErol.md
12.08.2022, 15.08.2022 ve 16.08.2022 tarihlerinin günlükleri eklendi. #287
> [feature]-[287]-[semver:minor]-Diary güncellendi.

- Interns/SimgeTerzioglu.md
> [feature]-[325]-[semver:minor]-Diary güncellendi.

- Interns/FelatAslan.md
> [feature]-[321]-[semver:minor]-Diary güncellendi

- Interns/OmerUcuncu.md
> [feature]-[329]-[semver:minor]-Diary güncellendi.

- Interns/MuhammetDuzenli.md
> [feature]-[338]-[semver:minor]-Diary güncellendi.

- Interns/ErayDanaci.md
> [feature]-[335]-[semver:minor]-Diary güncellendi.

- Interns/SimgeTerzioglu.md
> [feature]-[340]-[semver:minor]-Diary güncellendi.

- Interns/BurakKucuk.md
> [feature]-[331]-[semver:minor]-Diary güncellendi.

- Interns/FelatAslan.md
> [feature]-[342]-[semver:minor]-Diary güncellendi

- Interns/MuhammetDuzenli.md
> [feature]-[349]-[semver:minor]-Diary güncellendi.

- Interns/RahimeTurkmen.md
> [feature]-[346]-[semver:minor]-Diary update

- Interns/OmerUcuncu.md
> [feature]-[347]-[semver:minor]-Diary güncellendi.

- Interns/KeremErkubilay.md
> [feature]-[341]-[semver:minor]-Diary güncellendi.

- Interns/SimgeTerzioglu.md
> [feature]-[354]-[semver:minor]-Diary güncellendi.

- Interns/KeremErkubilay.md
> [feature]-[351]-[semver:minor]-Diary güncellendi.

- Interns/AliHanPertek.md
> [feature]-[333]-[semver:minor]-Diary güncellendi.

- Interns/FelatAslan.md
> [feature]-[358]-[semver:minor]-Diary güncellendi

- Interns/SimgeTerzioglu.md
> [feature]-[364]-[semver:minor]-Diary güncellendi.

- Interns/OmerUcuncu.md
> [feature]-[360]-[semver:minor]-Diary güncellendi.

- Interns/MuhammetDuzenli.md
> [feature]-[363]-[semver:minor]-Diary güncellendi.

- Interns/KeremErkubilay.md
> [feature]-[361]-[semver:minor]-Diary güncellendi.

- Interns/RahimeTurkmen.md
> [feature]-[368]-[semver:minor]-Diary update

- Interns/FelatAslan.md
> [feature]-[370]-[semver:minor]-Diary güncellendi

- Interns/ErayDanaci.md
> [feature]-[380]-[semver:minor]-Diary güncellendi.

- Interns/MuhammetDuzenli.md
> [feature]-[377]-[semver:minor]-Diary güncellendi

- Interns/EsraYelmen.md
16.08.2022, 17.08.2022, 18.08.2022 ve 19.08.2022 tarihlerine ait günlükler eklendi. #382
> [feature]-[382]-[semver:minor]-Diary güncellendi

- Interns/AliHanPertek.md
> [feature]-[375]-[semver:minor]-Diary güncellendi.

- Interns/OmerUcuncu.md
> [feature]-[384]-[semver:minor]-Diary güncellendi.

- Interns/ÖmerHamsi.md
> [feature]-[373]-[semver:minor]-Diary güncellendi

- Interns/FelatAslan.md
> [feature]-[388]-[semver:minor]-Diary güncellendi.

- Interns/KeremErkubilay.md
> [feature]-[372]-[semver:minor]-Diary güncellendi

- Interns/SimgeTerzioglu.md
> [feature]-[386]-[semver:minor]-Diary güncellendi.

- Interns/RahimeTurkmen.md
> [feature]-[390]-[semver:minor]-Diary update

- Interns/FelatAslan.md
> [feature]-[405]-[semver:minor]-Diary güncellendi

- Interns/MuhammetDuzenli.md
> [feature]-[398]-[semver:minor]-Diary güncellendi

- Interns/OmerUcuncu.md
> [feature]-[400]-[semver:minor]-Diary güncellendi.

- Interns/SimgeTerzioglu.md
> [feature]-[403]-[semver:minor]-Diary güncellendi.

- Interns/MuhammetDuzenli.md
> [feature]-[410]-[semver:minor]-Diary güncellendi

- Interns/EsraYelmen.md
> [feature]-[407]-[semver:minor]-Diary güncellendi

- Interns/OmerUcuncu.md
> [feature]-[409]-[semver:minor]-Diary güncellendi.

- Interns/FelatAslan.md
> [feature]-[413]-[semver:minor]-Diary güncellendi

- Interns/KeremErkubilay.md
> [feature]-[401]-[semver:minor]-Diary güncellendi

- Interns/SimgeTerzioglu.md
> [feature]-[417]-[semver:minor]-Diary güncellendi.

- Interns/ÖmerHamsi.md
> [feature]-[421]-[semver:minor]-Diary güncellendi.

- Interns/MuhammetDuzenli.md
> [feature]-[432]-[semver:minor]-Diary güncellendi

- Interns/UmmugulsumErol.md
> [feature]-[429]-[semver:minor]-Diary güncellendi.

- Interns/SimgeTerzioglu.md
> [feature]-[434]-[semver:minor]-Diary güncellendi.

- Interns/BurakKucuk.md
> [feature]-[439]-[semver:minor]-Diary güncellendi.

- Interns/KeremErkubilay.md
> [feature]-[427]-[semver:minor]-Diary güncellendi.

- Interns/OmerUcuncu.md
> [feature]-[436]-[semver:minor]-Diary güncellendi.

- Interns/AliHanPertek.md
> [feature]-[443]-[semver:minor]-Diary güncellendi.

- Interns/ErayDanaci.md
> [feature]-[441]-[semver:minor]-Diary güncellendi.

- Interns/EsraYelmen.md
> [feature]-[445]-[semver:minor]-Diary güncellendi.

- README.md
- docs/Git-Branch.md
#75 
closed bimser-intern/surveysaurus-pm#97
> [feature]-[75]-[semver:minor]-Git Branch Sunum Dokümani Hazirlandi.

- Interns/FelatAslan.md
> [feature]-[449]-[semver:minor]-Diary güncellendi

- README.md
- docs/Scrum.md
> [feature]-[465]-[semver:minor]-Scrum Docs Eklendi.

- Interns/MuhammetDuzenli.md
> [feature]-[458]-[semver:minor]-Diary güncellendi

- Interns/ÖmerHamsi.md
> [feature]-[452]-[semver:minor]-Diary güncellendi

- Interns/ErayDanaci.md
> [feature]-[461]-[semver:minor]-Diary güncellendi.

- Interns/FelatAslan.md
> [feature]-[471]-[semver:minor]-Diary güncellendi

- Interns/KeremErkubilay.md
> [feature]-[467]-[semver:minor]-Diary güncellendi.

- Interns/EsraYelmen.md
> [feature]-[474]-[semver:minor]-Diary güncellendi.

- Interns/SimgeTerzioglu.md
- README.md
- docs/Markdown-Markup-Language.md
#469 
#71 
closed bimser-intern/surveysaurus-pm#98
> [feature]-[469]-[semver:minor]-Diary güncellendi ve Markdown sunumu eklendi.

- docs/Git-Branch.md
#75 
closed https://github.com/bimser-intern/surveysaurus-pm/issues/97
> [feature]-[75]-[semver:minor]-Git Branch Komutlar Sunum Dokümanı Eklendi.

- docs/Scrum.md
> [feature]-[481]-[semver:minor]-Scrum dokümantasyonuna eklemeler yapıldı.

- README.md
- docs/Git-Giris-Kurulum.md
> [feature]-[488]-[semver:minor]-Git Giriş Ve Kurulum Sunumu eklendi.

- Interns/MuhammetDuzenli.md
> [feature]-[499]-[semver:minor]-Diary güncellendi

- README.md
- docs/GitHub.md
> [feature]-[478]-[semver:minor]-GitHub Sunumu eklendi.

- Interns/ErayDanaci.md
> [feature]-[494]-[semver:minor]-Diary güncellendi.

- Interns/OmerUcuncu.md
> [feature]-[480]-[semver:minor]-Diary güncellendi.

- Interns/AliHanPertek.md
> [feature]-[496]-[semver:minor]-Diary güncellendi.

- Interns/SimgeTerzioglu.md
> [feature]-[479]-[semver:minor]-Diary güncellendi.

- Interns/RahimeTurkmen.md
> [feature]-[506]-[semver:minor]-Diary güncellendi

- Interns/FelatAslan.md
> [feature]-[492]-[semver:minor]-Diary güncellendi.

- Interns/EsraYelmen.md
> [feature]-[502]-[semver:minor]-Diary güncellendi.

- README.md
- docs/Kotlin.md
> [feature]-[486]-[semver:minor]-Kotlin sunumu eklendi.

- Interns/KeremErkubilay.md
> [feature]-[490]-[semver:minor]-Diary güncellendi.

- Interns/ÖmerHamsi.md
> [feature]-[516]-[semver:minor]-Diary güncellendi.

- Interns/SimgeTerzioglu.md
> [feature]-[515]-[semver:minor]-Diary güncellendi.

- Interns/OmerUcuncu.md
> [feature]-[511]-[semver:minor]-Diary güncellendi.

- Interns/MuhammetDuzenli.md
> [feature]-[513]-[semver:minor]-Diary güncellendi.

- Interns/UmmugulsumErol.md
25.08.2022, 26.08.2022 ve 29.08.2022 günlükleri eklendi. #519
> [feature]-[519]-[semver:minor]-Diary güncellendi.

- Interns/SelinAytenCengiz.md
> [feature]-[476]-[semver:minor]-Diary güncellendi.

- Interns/FelatAslan.md
> [feature]-[521]-[semver:minor]-Diary güncellendi.

- Interns/EsraYelmen.md
> [feature]-[523]-[semver:minor]-Diary güncellendi.

- Interns/FelatAslan.md
> [feature]-[536]-[semver:minor]-Diary güncellendi.

- Interns/ErayDanaci.md
> [feature]-[535]-[semver:minor]-Diary güncellendi.

- Interns/OmerUcuncu.md
> [feature]-[533]-[semver:minor]-Diary güncellendi.

- Interns/MuhammetDuzenli.md
> [feature]-[540]-[semver:minor]-Diary güncellendi

- Interns/RahimeTurkmen.md
> [feature]-[544]-[semver:minor]-Diary güncellendi

- Interns/SimgeTerzioglu.md
> [feature]-[547]-[semver:minor]-Diary güncellendi.

- Interns/EsraYelmen.md
> [feature]-[546]-[semver:minor]-Diary güncellendi.

- README.md
- docs/Devops-Engineer-Security-Engineer.md
> [feature]-[455]-[semver:minor]-Security Engineer ve DevOps Engineer dokümanı eklendi.

- Interns/BurakKucuk.md
> [feature]-[534]-[semver:minor]-Diary güncellendi.

- Interns/AliHanPertek.md
> [feature]-[525]-[semver:minor]-Diary güncellendi.

- README.md
- docs/Frontend.md
#504 
- Frontend sunumu eklendi.
> [feature]-[504]-[semver:minor]-Frontend Sunumu eklendi.

- Interns/MuhammetDuzenli.md
> [feature]-[555]-[semver:minor]-Diary güncellendi

- Interns/FelatAslan.md
> [feature]-[558]-[semver:minor]-Diary güncellendi

- Interns/SimgeTerzioglu.md
> [feature]-[557]-[semver:minor]-Diary güncellendi.

- Interns/OmerUcuncu.md
> [feature]-[552]-[semver:minor]-Diary güncellendi

- Interns/ÖmerHamsi.md
> [feature]-[565]-[semver:minor]-Diary güncellendi.

- Interns/ErayDanaci.md
> [feature]-[567]-[semver:minor]-Diary güncellendi.

- Interns/FelatAslan.md
> [feature]-[568]-[semver:minor]-Diary güncellendi.

- Interns/UmmugulsumErol.md
> [feature]-[572]-[semver:minor]-Diary güncellendi.

- Interns/MuhammetDuzenli.md
> [feature]-[577]-[semver:minor]-Diary güncellendi

- Interns/SimgeTerzioglu.md
> [feature]-[576]-[semver:minor]-Diary güncellendi.

- Interns/OmerUcuncu.md
> [feature]-[561]-[semver:minor]-Diary güncellendi.

- Interns/AliHanPertek.md
> [feature]-[580]-[semver:minor]-Diary güncellendi.

- Interns/RahimeTurkmen.md
> [feature]-[582]-[semver:minor]-Diary güncellendi.

- Interns/KeremErkubilay.md
> [feature]-[571]-[semver:minor]-Diary güncellendi.

- Interns/ÖmerHamsi.md
> [feature]-[585]-[semver:minor]-Diary güncellendi.

- Interns/OmerUcuncu.md
> [feature]-[584]-[semver:minor]-Diary güncellendi

- Interns/MuhammetDuzenli.md
> [feature]-[591]-[semver:minor]-Diary güncellendi

- Interns/KeremErkubilay.md
> [feature]-[587]-[semver:minor]-Diary güncellendi.

- Interns/OmerUcuncu.md
> [feature]-[596]-[semver:minor]-Diary güncellendi

- Interns/EsraYelmen.md
> [feature]-[598]-[semver:minor]-Diary güncellendi.

- Interns/SimgeTerzioglu.md
> [feature]-[600]-[semver:minor]-Diary güncellendi.

- Interns/FelatAslan.md
> [feature]-[607]-[semver:minor]-Diary güncellendi

- Interns/BurakKucuk.md
> [feature]-[613]-[semver:minor]-Diary güncellendi

- Interns/OmerUcuncu.md
> [feature]-[604]-[semver:minor]-Diary güncellendi

- Interns/ErayDanaci.md
> [feature]-[618]-[semver:minor]-Diary güncellendi

- Interns/FelatAslan.md
> [feature]-[621]-[semver:minor]-Diary güncellendi

- Interns/SimgeTerzioglu.md
> [feature]-[626]-[semver:minor]-Diary güncellendi.

- Interns/UmmugulsumErol.md
> [feature]-[628]-[semver:minor]-Diary güncellendi.

- Interns/RahimeTurkmen.md
> [feature]-[605]-[semver:minor]-Diary güncellendi

- Interns/AbdullahBodur.md
> [feature]-[610]-[semver:minor]-Diary güncellendi

- Interns/ErayDanaci.md
> [feature]-[630]-[semver:minor]-Diary güncellendi

- Interns/OmerUcuncu.md
> [feature]-[614]-[semver:minor]-Diary güncellendi

- Interns/SimgeTerzioglu.md
> [feature]-[635]-[semver:minor]-Diary güncellendi.

- Interns/OmerUcuncu.md
> [feature]-[624]-[semver:minor]-Diary güncellendi

- Interns/FelatAslan.md
> [feature]-[633]-[semver:minor]-Diary güncellendi

- README.md
- docs/Git-Temelleri.md
> [feature]-[637]-[semver-minor]-Git temelleri sunumu eklendi.

- Interns/SimgeTerzioglu.md
> [feature]-[639]-[semver:minor]-Diary güncellendi.

- Interns/FelatAslan.md
- README.md
- docs/Redis.md
- docs/Sass.md
>  [feature]-[643]-[semver:minor]-Redis ve Sass sunumları eklendi.

- Interns/FelatAslan.md
> [feature]-[641]-[semver:minor]-Diary güncellendi.

- Interns/RahimeTurkmen.md
> [feature]-[647]-[semver:minor]-Diary güncellendi.
